name: Auto-Label
on:
  issues:
    types: [opened, edited, closed]  # 添加closed事件以捕获关闭操作
    reopen: true  # 可选：如果希望重新打开issue时也触发

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label based on content and status
        id: auto_label
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = (issue.body || "").toLowerCase();
            const closingReason = issue.state_reason || "";
            
            // 定义关键词与标签映射
            const keywordMap = [
              { keywords: ["done", "fixed"], label: "✅ Complete" },
              { keywords: ["not plan", "not planned", "no plan", "wontfix"], label: "❌ wontfix" },
              { keywords: ["duplicate", "duplicated", "dupe", "duplicate issue"], label: "❌ duplicate" }
            ];
            
            let labelsToAdd = new Set();
            
            // 检查关闭原因 (GitHub API返回的是"not_planned"而不是"not planned")
            if (closingReason.toLowerCase() === "not_planned") {
              labelsToAdd.add("❌ wontfix");
            }
            
            // 检查正文中的关键词
            keywordMap.forEach(({ keywords, label }) => {
              if (keywords.some(kw => body.includes(kw))) {
                labelsToAdd.add(label);
              }
            });
            
            // 返回逗号分隔的标签列表
            return Array.from(labelsToAdd).join(',');
          result-encoding: string

      - name: Apply labels
        if: steps.auto_label.outputs.result != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.auto_label.outputs.result }}
