name: Auto-Label
on:
  issues:
    types: [opened, edited, closed] 

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label based on content and status
        id: auto_label
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = (issue.body || "").toLowerCase();
            const closingReason = issue.state_reason || "";
            
            const keywordMap = [
              { keywords: ["\\bdone\\b", "\\bfixed\\b"], label: "✅ Complete" },  // 使用单词边界
              { keywords: ["\\bnot\\s+plan", "\\bwont\\s?fix\\b", "no\\s+plan"], label: "❌ wontfix" },
              { 
                keywords: [
                  "\\bduplicate\\b",     // 完整单词
                  "\\bdupe\\b",          // 常见缩写
                  "\\bdup\\b",           // 极简缩写
                  "already reported"     // 同义表述
                ], 
                label: "❌ duplicate" 
              }
            ];
            
            let labelsToAdd = new Set();
            
            // 处理 GitHub 关闭原因
            if (closingReason.toLowerCase() === "not_planned") {
              labelsToAdd.add("❌ wontfix");
            }
            
            // 检测正文关键词（使用正则匹配）
            keywordMap.forEach(({ keywords, label }) => {
              const regexes = keywords.map(kw => new RegExp(kw, "i"));  // 创建正则表达式数组
              if (regexes.some(regex => regex.test(body))) {
                labelsToAdd.add(label);
              }
            });
            
            console.log(`Detected labels: ${Array.from(labelsToAdd).join(', ')}`);
            return Array.from(labelsToAdd).join(',');
          result-encoding: string

      - name: Apply labels
        if: steps.auto_label.outputs.result != ''
        uses: actions/github-script@v6
        with:
          script: |
            const labels = '${{ steps.auto_label.outputs.result }}'.split(',');
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
            console.log(`Added labels: ${labels.join(', ')}`);
